### ISSUE TITLE
Modules need to be updated to accomodate changes in Canary EdXposed &Riru v.22+ 

### ISSUE THREAD

**Issue by otonieru** [Firefds/FirefdsKit#13]
UPDATE : As per 30 Dec '20. Stable 6 Version works with bellow combination :

- Magisk 21.2
- Riru 23.1
- EdXposed 5.1.4_4655
- Firefds Stable-6 from : https://drive.google.com/file/d/1PMNDbkxp_WcccSGzTX7-guBR8-HLuf96/view?usp=sharing

EDIT : Module itself doesnt use Riru, but it's dependency on EdXposed causing issue when Canary version of EdXposed (which released with compatibility for new Riru Core) is being used. 

Modules wont work with Riru v22 and newer because of some changes in Riru itself.

Rikka has stated that all modules neednto be updated so it can work along new Riru

**Comment by Firefds** [comment]
The modules that need to change are the ones that use Riru, in this case - EdXposed. FirefdsKit doesn't use Riru.

**Comment by otonieru** [comment]
Well maybe i put a wrong question then, 

EdXposed itself is working on Riru v22+ by using Canary versions

So maybe the issue is that Stable Firefds (neither GravityBox if that matter) is not working on Canary EdXposed. 

Is there any "canary" Firefds (i dont think so ?)

**Comment by Firefds** [comment]
Please find these test versions. They will work only with Riru 23+ and EdXposed Canary 5.1.0 + 
Firefds Kit PIE - https://drive.google.com/file/d/1YTpuYYgsG7mr07jSUAmbBSZE9IaemWsi/view?usp=sharing
Firefds Kit Q - https://drive.google.com/file/d/1XQ8RhuEdUOHYogOIqXg88OFH8iaLsT_X/view?usp=sharing

**Comment by otonieru** [comment]
> Please find these test versions. They will work only with Riru 23+ and EdXposed Canary 5.1.0 +
> Firefds Kit PIE - https://drive.google.com/file/d/1YTpuYYgsG7mr07jSUAmbBSZE9IaemWsi/view?usp=sharing
> Firefds Kit Q - https://drive.google.com/file/d/1XQ8RhuEdUOHYogOIqXg88OFH8iaLsT_X/view?usp=sharing

Thank you for heads up. I tried it, unfortunately it said the module is not active. In EdXposed manager the toggle was already active.

Also, the "allow change system setting" is greyed out

![Screenshot_20201214-104932_Firefds Kit  Q](https://user-images.githubusercontent.com/9674184/102038646-61641780-3dfa-11eb-80ec-0388e007bee3.jpg)

![Screenshot_20201214-104927_Settings](https://user-images.githubusercontent.com/9674184/102038669-72148d80-3dfa-11eb-9f71-0c0fec24b7d9.jpg)

Here's Module Logs if you need it : https://mega.nz/file/uk8AHBJT#aDBL-3SZ6YnMszD01kFU9Q8mDK7mOIJ97wosZJIC7pE

Just for reference, Stable-5 version can be Activated without issue. It just that the mod is not working.

**Comment by Firefds** [comment]
@otonieru please try the following - 
1. Uninstall Firefds Kit
2. Reboot
3. Reinstall Firefds Kit
4. Enable in EdXposed Manager
5. Reboot
6. Try to open the app again

**Comment by Firefds** [comment]
@otonieru If that doesn't work, please try this, with the same steps
https://drive.google.com/file/d/1XQ8RhuEdUOHYogOIqXg88OFH8iaLsT_X/view?usp=sharing

**Comment by otonieru** [comment]
> @otonieru If that doesn't work, please try this, with the same steps
> https://drive.google.com/file/d/1XQ8RhuEdUOHYogOIqXg88OFH8iaLsT_X/view?usp=sharing

Tried steps above. Uninstall - Reboot - Install - Activate - Reboot. 

It still hasnt allowed me to turn on the Change System Setting permissions. And unfortunately it still say Module Not Active when app is launched.

Do Firefds specifically need Root Access ? Because it never prompt to gain a root access.

**Comment by binarynoise** [comment]
That might be stupid question, but don't you need to declare a permission in the manifest to write the settings? For me that would be the reason why the option to enable the permission is greyed out

**Comment by otonieru** [comment]
> That might be stupid question, but don't you need to declare a permission in the manifest to write the settings? For me that would be the reason why the option to enable the permission is greyed out

I believe in normal case. Yes. But normally for xposed module, it should be handled properly by xposed. Very reason it doesnt work this moment is because it has compatibility issue with canary EdXposed & Latest Riru

**Comment by binarynoise** [comment]
What is the last combination of riru, EdXposed and modules that is known to work properly?

**Comment by otonieru** [comment]
> What is the last combination of riru, EdXposed and modules that is known to work properly?

Based on known info : Riru 21.6 + EdXposed Alpha 0.4.x.x + Firefds Stable 5

Problem is, EdXposed 0.4.x.x and Riru 21.6 won't work properly on One UI 2.5 . It will simply said that xposed is installed but not active doesnt matter how i tried (clean install etc) and other problem is that 0.4.x version wont pass safetynet. 

I dont really care about safetynet, but if it can't be made active, no modules would work anyway, including Firefds. 

So for me at this moment, no combination is working for Firefds. 

Other modules work just fine with my current configuration :

Riru 23.1
EdXposed Alpha 0.5.1.3_4646 YAHFA

**Comment by otonieru** [comment]
> @otonieru If that doesn't work, please try this, with the same steps
> https://drive.google.com/file/d/1XQ8RhuEdUOHYogOIqXg88OFH8iaLsT_X/view?usp=sharing

EdXposed is releasing 0.5.1.3_4646 as latest Alpha (no longer in Canary stage) with full support for Riru 23+. Hopefully Firefds Stable 6 will work soon enough 🙏🏼

**Comment by binarynoise** [comment]
> That might be stupid question, but don't you need to declare a permission in the manifest to write the settings? For me that would be the reason why the option to enable the permission is greyed out

I had a quick look at the source. I think we don't actually need the permission for now. The only two occurrences of writing System Settings are either unused or within a hook (SystemUI should have the permission anyway).

For the error message, that pops up, it's *only* the xposed check that fails. It hasn't checked for root yet and as the app doesn't have a dependency on some superuser lib, I assume the app doesn't even need root.

PS: merry Christmas

**Comment by Firefds** [comment]
So, I've got a mix of good news - bad news:

Good news -
* I finally got Q OneUI 2.5 for my S8, thanks to HadesROM!
* The Pie version works with a certain Riru + EdXposed combination (post changes)

Bad news - 
* Pie version doesn't work with latest Riru + EdXposed combination. Will try to figure out which combination does work.
* Q version didn't work at all. Now that I have Q I will try to make it work
* Don't expect a solution soon. They changed a lot of things in EdXposed and I don't have much time to work on this, mainly on weekends.  I see that C3C0, the creator of GravityBox, has some issues as well.

Additional stuff I saw that was raised here -
* FirefdsKit doesn't use root anymore. It used to use root to change CSC files, but I moved all the behavior to pure Xposed. I haven't updated that text though 😄 
* System permissions are given using Xposed methods. You will not be able to enable that switch when the system asks for it, just ignore it and press the back button.

**Comment by Firefds** [comment]
@otonieru @binarynoise it seems the Android Q port for the S8 has too many changes. I did however found a bug I had with some previous test builds. Please try this version for Android Q -
https://drive.google.com/open?id=1zm0V1CkMsl2PIqN5b3rVBsw2wIXVUaSO

**Comment by ErdbeerbaerLP** [comment]
I tried that version and it says it's activated, but enabling any feature (like advanced power menu) doesn't change anything after rebooting

Edit: Fake system status works.
Seeing that, is it safe to do an android update from system settings? (do I keep magisk and stuff?)

**Comment by binarynoise** [comment]
Some thing that also works is the notifications panel native blur but it can't be disabled.

@ErdbeerbaerLP no, you'll most probably lose magisk and stuff. The magisk manual says that you must never ever flash a stock image that hasn't been patched again. If you lose magisk, you'll need to do a complete reinstall losing all your data

Edit: for me system status is (still?) set to custom

**Comment by otonieru** [comment]
> So, I've got a mix of good news - bad news:
> 
> Good news -
> 
> * I finally got Q OneUI 2.5 for my S8, thanks to HadesROM!
> * The Pie version works with a certain Riru + EdXposed combination (post changes)
> 
> Bad news -
> 
> * Pie version doesn't work with latest Riru + EdXposed combination. Will try to figure out which combination does work.
> * Q version didn't work at all. Now that I have Q I will try to make it work
> * Don't expect a solution soon. They changed a lot of things in EdXposed and I don't have much time to work on this, mainly on weekends.  I see that C3C0, the creator of GravityBox, has some issues as well.
> 
> Additional stuff I saw that was raised here -
> 
> * FirefdsKit doesn't use root anymore. It used to use root to change CSC files, but I moved all the behavior to pure Xposed. I haven't updated that text though 😄
> * System permissions are given using Xposed methods. You will not be able to enable that switch when the system asks for it, just ignore it and press the back button.

Thank you for brief explanation. Let me try the version you link bellow. Dont let us mess your end of year holiday btw. Wish u a healthy joyful time.

**Comment by otonieru** [comment]
> Some thing that also works is the notifications panel native blur but it can't be disabled.
> 
> @ErdbeerbaerLP no, you'll most probably lose magisk and stuff. The magisk manual says that you must never ever flash a stock image that hasn't been patched again. If you lose magisk, you'll need to do a complete reinstall losing all your data
> 
> Edit: for me system status is (still?) set to custom

It's not that it cant be disabled. It just that native blur was there by default in One UI 2.5, LoL

@Firefds i can second the info above btw, module was activated successfully. But non of the functions work

And if it's matter. The module doest able to restart the device using the prompt on notification. So i think some permissions (normally root permission is needed to be able to restart device) still missing.

**Comment by otonieru** [comment]
> I tried that version and it says it's activated, but enabling any feature (like advanced power menu) doesn't change anything after rebooting
> 
> Edit: Fake system status works.
> Seeing that, is it safe to do an android update from system settings? (do I keep magisk and stuff?)

Never do update from setting, especially if you are like me, who doesnt have TWRP available yet for the device. (Am on Galaxy Z Flip)

**Comment by ErdbeerbaerLP** [comment]
OK so I need to do that via Odin then. Also no TWRP yet. (Galaxy a70).

But I hope that the advanced power menu will work again soon, as I always need to boot into recovery instead of stock system

**Comment by binarynoise** [comment]
> But I hope that the advanced power menu will work again soon, as I always need to boot into recovery instead of stock system

For now you can use the reboot options from magisk manager or EdXposed manager

**Comment by Firefds** [comment]
I managed to fix the issue I had with Hades ROM by replacing it's SystemUI.apk with a stock one from the N9's Android Q.
I'm not sure how, but everything seems to work out of the box for me, with the current Firefds Kit STABLE-5 version, Latest Riru and Latest EdXposed.
The steps I did were:
* Remove any existing Riru and EdXposed
* Reboot and clear cache
* Install Riru 21.1
* Reboot
* Install EdXposed 4.6.3 (4546)
* Reboot
* Install Firefds Kit Q
* Reboot
* Made sure everything is working
* Remove Riru and EdXposed
* Reboot
* Install Riru 23.1
* Reboot
* Install EdXposed  5.1.3_4653 (Latest Canary)
* Reboot
* Checked Firefds Kit and GravityBox Q - both seem to work.

Now, maybe this is just because I'm using a port rom. If this doesn't work for you guys, nothing much I can do. You will have to wait until I'll be able to afford a new device, which won't happen in the near future. Probably only when my S8 dies completely...

![Screenshot_20201227-112611_EdXposed Manager](https://user-images.githubusercontent.com/18083277/103175351-60d67280-4837-11eb-8895-3510c5e5f238.jpg)
![Screenshot_20201227-112624](https://user-images.githubusercontent.com/18083277/103175352-616f0900-4837-11eb-9264-7bb30d02fa8b.jpg)
![Screenshot_20201227-112635](https://user-images.githubusercontent.com/18083277/103175350-60d67280-4837-11eb-8d14-a5fadce90c70.jpg)

**Comment by Firefds** [comment]
I think I figured it out , give this a shot!
https://drive.google.com/file/d/1PMNDbkxp_WcccSGzTX7-guBR8-HLuf96/view?usp=sharing

**Comment by otonieru** [comment]
> I think I figured it out , give this a shot!
> https://drive.google.com/file/d/1PMNDbkxp_WcccSGzTX7-guBR8-HLuf96/view?usp=sharing

Hi, appreciate it. Unfortunately it still wont work on my Z Flip

Probably i need a clean install of the whole Riru & EdXposed and doing downgrade version of it like what you mentioned above, 

unfortunately on Z flip, it's kinda troublesome to find version of riru & edxposed that really works. 21 something and alpha 4.x.x doesnt work at all. 

So thank you so much for the effort. But right now am not in a situation to be able to try a full cleanup of riru & xposed. 🙏🏼

Maybe i'll just try to update to latest Canary, since i saw you are on 4653. (am still on 4646) 

am on Magisk 21.2 if that matter btw.

**Comment by Firefds** [comment]
You will need Riru 23.1 and EdXposed 0.5.1.4 4655. This version is confirmed to work only with these settings and Android Q

**Comment by otonieru** [comment]
> You will need Riru 23.1 and EdXposed 0.5.1.4 4655. This version is confirmed to work only with these settings and Android Q

Okay, will try that now 🙏🏼

**Comment by otonieru** [comment]
> You will need Riru 23.1 and EdXposed 0.5.1.4 4655. This version is confirmed to work only with these settings and Android Q

Man, You did it ! 4655 and it works straight away. 👍🏻👍🏻👍🏻

**Comment by dcoolArne** [comment]
Hey could you mayby realease the working Version, i have the same problems as otonieru under android 9 on my S9, and building the app myself doesn't work for me.

**Comment by binarynoise** [comment]
This has already been fixed, make sure you use the correct versions:
- [Firefds latest release for Q](https://github.com/Firefds/FirefdsKit/releases/tag/v1.0.1.4)
  No fix for Pie (yet)
- [Edxposed latest alpha release](https://github.com/ElderDrivers/EdXposed/releases/tag/v0.5.1.4)
- [Riru latest release](https://github.com/RikkaApps/Riru/releases/tag/v23.1)

(see [this comment above](https://github.com/Firefds/FirefdsKit/issues/13#issuecomment-752305443))

**Comment by dcoolArne** [comment]
I have the latest riru and edxposed, but i am on android p not q. Can i still use the q version?

**Comment by otonieru** [comment]
> @dcoolArne This has already been fixed, make sure you use the correct versions:
> 
> * [Firefds latest release](https://github.com/Firefds/FirefdsKit/releases/tag/v1.0.1.4)
> * [Edxposed latest alpha release](https://github.com/ElderDrivers/EdXposed/releases/tag/v0.5.1.4)
> * [Riru latest release](https://github.com/RikkaApps/Riru/releases/tag/v23.1)
> 
> (see [this comment above](https://github.com/Firefds/FirefdsKit/issues/13#issuecomment-752305443) )

I think the problem is that he was still on Pie. Not Q. The latest fix was for Q build. But i can be wrong if turned out there is another release for P.

**Comment by binarynoise** [comment]
@dcoolArne The Pie version did not get the fix (yet).  
I updated my comment above

**Comment by dcoolArne** [comment]
Then it seems like i have to wait a little bit longer, just asked to make sure that i didn't miss anything.

**Comment by Firefds** [comment]
Ah right, I haven't released the Pie fix yet.. maybe later this weekend

**Comment by Firefds** [comment]
@dcoolArne Let me know if this version works for you - 
https://drive.google.com/file/d/1o3i1sBt6eU-_tAfu8b40RucBCyvma0cO/view?usp=sharing

**Comment by dcoolArne** [comment]
Doesn't work for me, but i get a bunch of usb disconnects on bootup and the system ui also takes longer to feel "smooth". I tried removing the old app, reboot, install the new app, reboot, change some settings(fingerprint after reboot, seconds on clock) reboot again. But i didn't apply anything.

**Comment by Firefds** [comment]
> Doesn't work for me, but i get a bunch of usb disconnects on bootup and the system ui also takes longer to feel "smooth". I tried removing the old app, reboot, install the new app, reboot, change some settings(fingerprint after reboot, seconds on clock) reboot again. But i didn't apply anything.

Make sure you are using latest Riru and EdXposed. Also please make sure you are whitelisting all the needed processes. You can find a list in the README file.

If it still doesn't work, please send logs

**Comment by dcoolArne** [comment]
I updated to edxposed 4655, and it worked for one reboot. Then i switch more settings on and it stoped working. Network speed, seconds on clock and unlock after reboot worked, if i only turn these features on. What logs do you need? I'm not in whitelist mode.

**Comment by Firefds** [comment]
> I updated to edxposed 4655, and it worked for one reboot. Then i switch more settings on and it stoped working. Network speed, seconds on clock and unlock after reboot worked, if i only turn these features on. What logs do you need? I'm not in whitelist mode.

Xposed module logs please

**Comment by dcoolArne** [comment]
[EdXposed_Verbose_20210102_215954.txt](https://github.com/Firefds/FirefdsKit/files/5760855/EdXposed_Verbose_20210102_215954.txt)
Hope this is the correct one.

**Comment by Firefds** [comment]
@dcoolArne please try this version - 
https://drive.google.com/open?id=1o3i1sBt6eU-_tAfu8b40RucBCyvma0cO

**Comment by dcoolArne** [comment]
Everthing works now, except fakeing system status to official. But that also didn't work on the old version, bevor the riru changes.

**Comment by otonieru** [comment]
@Firefds this might be out of topic question. But can you try on your side, i notice some of my apps (which serve similar functions) stop working after installing latest Firefds. It will simply freeze upon app launch, 

the app is : Brevent and AppOps 

if you dont mind, can you try whether the app working on your phone or not ?
