### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by greatwitedragon** [Firefds/FirefdsKit#16]
Hi when I open the app it comes up with allow modify system settings but the option and the toggle are greyed out

I'm using a Samsung s7 edge hero2lite
Running linage OS 18.1
I have the latest Riru on magisk and have attached a screenshot with the modules in using for edxposed
![Screenshot_20210205-205926_Pixel_Launcher](https://user-images.githubusercontent.com/78621219/107088635-288e6080-67f5-11eb-8aca-feca31bb059d.png)
Hope you can help

**Comment by Firefds** [comment]
that's expected. you can ignore it.
