### ISSUE TITLE
Xsharedpreference Failing to read prefs file above SDK 24

### ISSUE THREAD

**Issue by Android1500** [Firefds/FirefdsKit#17]
how uhh read prefs xml file for your module above SDK 24 coz as we knw we cant read preference.xml MODE_WORLD_READABLE not work in sdk > 24 any idea how to make preference readable on sdk > 24

**Comment by Firefds** [comment]
This is not an issue.
You can read all about pref files with new edxposed here
https://github.com/ElderDrivers/EdXposed/wiki/New-XSharedPreferences

**Comment by Android1500** [comment]
> This is not an issue.
> 
> You can read all about pref files with new edxposed here
> 
> https://github.com/ElderDrivers/EdXposed/wiki/New-XSharedPreferences

But I think it's works if user installed edxposed but what about rovo xpose which supported Oreo I think new Xsharedpreference not for old xposed
