### ISSUE TITLE
[BUG] Network monitor shows triple the bandwidth actually used when connected to a VPN

### ISSUE THREAD

**Issue by techIndia-hacker** [Firefds/FirefdsKit#19]
**Describe the bug**
Wrong network speed displayed. I have verified this when testing bandwidth using ookla and Adguard connected in vpn mode. It shows twice than really used.

**Device:**
 - Device: Galaxy M40
 - Chipset: Snapdragon 675
 - Model: SM-M405F

This bug also happened in GravityBoz. But it was solved in cooperation with 2 developers

**Screenshots**

**Comment by techIndia-hacker** [comment]
For reference

https://github.com/GravityBox/GravityBox/issues/2087

**Comment by Firefds** [comment]
While I understand the issue, I'm not implementing my own traffic meter like GravityBox does, but just enabling the pre built Samsung one.
I'm not interesting in fixing Samsung bugs, and don't have time to do that, sorry.

**Comment by techIndia-hacker** [comment]
Should I open an issue in Samsung community to fix this bug since Samsung doesn't officially have any network meter?

Samsung doesn't have any pre-built bandwidth meter as far as I know🤔🤔

@Firefds
