### ISSUE TITLE
Android 14

### ISSUE THREAD

**Issue by CompuGeniusCode** [Firefds/FirefdsKit#38]
Does this work on Android 14? I'm afraid to try at risk of bricking my device.
Are there any plans to update it, and/or any alternatives I can use?

**Comment by Firefds** [comment]
No Android 14 version yet. Once my device gets updated and I'll have the time, I'll work on a A14 version.

**Comment by CompuGeniusCode** [comment]
> No Android 14 version yet. Once my device gets updated and I'll have the time, I'll work on a A14 version.

Alright, great! Thanks for the fast reply 😀

**Comment by Tupu4545** [comment]
> No Android 14 version yet. Once my device gets updated and I'll have the time, I'll work on a A14 version.

Is it safe for me to use the A13 version on my galaxy running latest one ui 6 with a14?

**Comment by Firefds** [comment]
> > No Android 14 version yet. Once my device gets updated and I'll have the time, I'll work on a A14 version.
> 
> Is it safe for me to use the A13 version on my galaxy running latest one ui 6 with a14?

No, it will not work.

**Comment by ItsMadruga** [comment]
When you released the version for A14 I ran to test it and it didn't work for me. 😢

@Firefds

**Comment by Firefds** [comment]
Android 14 version ALPHA 2 is out with bug fixes.

**Comment by CompuGeniusCode** [comment]
@Firefds it doesn't seem to work on my Samsung S23 Plus. I tried enabling Network Speed in Status Bar, Fake System Status to Official, and Allow Biometrics on Boot, and none work.
Am I missing something?

**Comment by Firefds** [comment]
> @Firefds it doesn't seem to work on my Samsung S23 Plus. I tried enabling Network Speed in Status Bar, Fake System Status to Official, and Allow Biometrics on Boot, and none work.
> Am I missing something?

Try the new version released today and attach logs if it doesn't work.

**Comment by CompuGeniusCode** [comment]
> > @Firefds it doesn't seem to work on my Samsung S23 Plus. I tried enabling Network Speed in Status Bar, Fake System Status to Official, and Allow Biometrics on Boot, and none work.
> > Am I missing something?
> 
> Try the new version released today and attach logs if it doesn't work.

That was the only version I tried lol. How do I get logs?

**Comment by Firefds** [comment]
> > > @Firefds it doesn't seem to work on my Samsung S23 Plus. I tried enabling Network Speed in Status Bar, Fake System Status to Official, and Allow Biometrics on Boot, and none work.
> > > Am I missing something?
> > 
> > Try the new version released today and attach logs if it doesn't work.
> 
> That was the only version I tried lol. How do I get logs?

Through the Lsposed app.

**Comment by CompuGeniusCode** [comment]
[LSPosed_2024-01-14T00_00_56.253515.zip](https://github.com/Firefds/FirefdsKit/files/13930385/LSPosed_2024-01-14T00_00_56.253515.zip)
This?

**Comment by Firefds** [comment]
> [LSPosed_2024-01-14T00_00_56.253515.zip](https://github.com/Firefds/FirefdsKit/files/13930385/LSPosed_2024-01-14T00_00_56.253515.zip)
> This?

The only issue I see regarding FirefdsKit is that Allow Biometrics on Boot doesn't work, which is possible. 

I see other errors in other modules.

1. Allow Biometrics on Boot may not work.
2. No other issues are shown.

In any case, this GitHub issue is closed as Android 14 version is released. 
If you are experiencing other issues, please open a different ticket.
