### ISSUE TITLE
[BUG] crashes on open

### ISSUE THREAD

**Issue by jnigrine** [Firefds/FirefdsKit#39]
Pixel 6 running Android 14. Rebooted after install and module activate. When I open the app  it closes right away, even before asking for root.

THANK YOU for bringing this back!

**Comment by ItsMadruga** [comment]
@jnigrine This module only works on Samsung devices if I'm not mistaken :)

**Comment by jnigrine** [comment]
> @jnigrine This module only works on Samsung devices if I'm not mistaken :)

Ah. I think a few versions ago, it supported more. Thanks.

**Comment by Firefds** [comment]
Than you for the interest, but this module never worked on any other device besides Samsung.
I did work on a GravityBox version for 13, which partially works, but I won't have time to do it for 14.

**Comment by jnigrine** [comment]
Thank you!

Jan 13, 2024 6:25:52 PM Shauli Bracha ***@***.***>:

**Comment by ItsMadruga** [comment]
@Firefds Hello, my device is a galaxy a54, running a14, I ran to test the module for a14 when it launched, but unfortunately none of the options are working for me, perhaps an error in XSharedPreferences, because even with the options activated, none of them work, and I already looked at its source code, and redid 1 of the functions, and it worked perfectly. If you could take a look I would appreciate it :)

**Comment by Firefds** [comment]
> @Firefds Hello, my device is a galaxy a54, running a14, I ran to test the module for a14 when it launched, but unfortunately none of the options are working for me, perhaps an error in XSharedPreferences, because even with the options activated, none of them work, and I already looked at its source code, and redid 1 of the functions, and it worked perfectly. If you could take a look I would appreciate it :)

I just released a new version that fixes XSharedPreferences. Please check it out.

**Comment by ItsMadruga** [comment]
> > @Firefds Hello, my device is a galaxy a54, running a14, I ran to test the module for a14 when it launched, but unfortunately none of the options are working for me, perhaps an error in XSharedPreferences, because even with the options activated, none of them work, and I already looked at its source code, and redid 1 of the functions, and it worked perfectly. If you could take a look I would appreciate it :)
> 
> I just released a new version that fixes XSharedPreferences. Please check it out.

Thanks, now it works
