### ISSUE TITLE
[REQUEST] Power Menu & Obligations

### ISSUE THREAD

**Issue by armync** [Firefds/FirefdsKit#4]
1) In normal mode (stock) if you want to shutdown the phone, you need to enter the PIN. But, in Magisk's custom recovery this isn't possible. Is there any way to protect that menu (without removing the shutdown and restart buttons)?
2) Can I ignore the Display Timeout? Any value that is set there is automatically applied to the settings, but I don't want it.

**Comment by Firefds** [comment]
1. Fixed 7311193ad946212bcdf338e7a4840439a9053ed4
2. Yes, just don't set anything there, it won't change your settings.
