### ISSUE TITLE
[BUG]Galaxy A73 5G Features does not work. System call recording disappears when module enabled.

### ISSUE THREAD

**Issue by dima8389** [Firefds/FirefdsKit#40]
Galaxy A73 5G, Android14, Firefds14-ALPHA1

Does not work (settings have no effect at all):
Clock customization.
Data traffic monitor.
Multiuser.
Power menu.

Braked feature:
Built in call recording works, when module is not activated. Disappears from menu and stops working when the module activated. All phone settings have no effect. Region ILO

**Comment by Tupu4545** [comment]
I can confirm I have the same issue however using an older version of this module made for android 13 let's me change clock settings Data traffic monitor broken in one ui 6 show seconds work power menu broken

**Comment by Firefds** [comment]
Android 14 version ALPHA 2 is out with bug fixes.

**Comment by dima8389** [comment]
Thank  you. It much better.
