### ISSUE TITLE
[BUG] Secure Flag still locks screenshots

### ISSUE THREAD

**Issue by alroy214** [Firefds/FirefdsKit#5]
**Describe the bug**
I can't take screenshot when secure flag is enabled.

**Device:**
 - Device: [e.g. Galaxy S8] Galaxy S10
 - Chipset: [Exynos/Snapdragon] Exynos
 - Model: [e.g. SM-G950F]

**Xposed or Logcat logs**
https://s.amsu.ng/6779x9x7TgqN

Refer here to how to get logs - https://github.com/rovo89/XposedBridge/wiki/Bugs#how-can-i-get-logs

**Screenshots**

**Additional context**

**Comment by Firefds** [comment]
@alroy214, I didn't see anything in the logs stating an error here. I also checked the code on the Galaxy S10 Android 10 version and it didn't change since Pie.
Please try again - 

1. Open Firefds Kit app
2. Click on the menu button
3. Security Hacks
4. Make sure the Secure Flag switch is on
5. Reboot and try again

**Comment by alroy214** [comment]
Hmm it's on, I rebooted a few times and still get a message that I can't screenshot, I can't really show it to you (cause I can't screenshot 😂)
That didn't happen on the pie but does happen on 10

**Comment by Firefds** [comment]
@alroy214 any chance you can provide xposed logs when repeating this?

**Comment by Firefds** [comment]
@alroy214 please check the version posted here, I think I implemented a fix for this https://forum.xda-developers.com/showpost.php?p=81746247&postcount=93
As it's a debug version, you will need to uninstall the previous Firefds Kit before installing this one.

**Comment by shayzour** [comment]
Hi there i have firefds kit but cant open secure folder although i used to use it before any help thanks guys

**Comment by Firefds** [comment]
@shayzour your issue has nothing to do with secure flag.
Please open a new issue and provide both verbose and module xposed logs

**Comment by shayzour** [comment]
Ok thank you its working fine after i update the app keep the good work
