### ISSUE TITLE
[REQUEST] Screen recorder now is merged in Samsung capture

### ISSUE THREAD

**Issue by NULL0B** [Firefds/FirefdsKit#6]
Screen recorder now is merged in Samsung on android 10 capture would be better to launch that activity instead installing screen recorder.
Other one
Default reboot in android i mean in framework change to reboot to recovery. this tweak is in smali patcher as magisk module would be better to have it in exposed since root is only possible via recovery boot.

**Comment by Firefds** [comment]
@NULLO0B Thank you for your comments!
I was working had on implementing the native screen recorder for a week now with some help of XDA users (since I don't have a device with Android 10), but no luck.
I'm attaching another version for you to try the native screen recorder. This is a debug version of the app, so you will have to uninstall the version you have now and install this one. (The fire is zipped because github doesn't allow apks, so you will need to unzip it first, sorry)

Regarding the default reboot - I got this comment back in Pie version, I don't want to replace the reboot option completely with the reboot to recovery because who knows what the future will bring.
BUT - A feature I did add to handle this is Custom Texts, and you can find it under  System --> Power Menu Options --> Custom Texts. Here you can change the text that appears under the reboot to recovery icon to say whatever you want it to say. Then you can remove the normal reboot from the power menu and that's it!
[FirefdsKit_Q_0.0.3.0-ALPHA-3-debug.apk.zip](https://github.com/Firefds/FirefdsKit/files/4192901/FirefdsKit_Q_0.0.3.0-ALPHA-3-debug.apk.zip)

**Comment by NULL0B** [comment]
@Firefds   Thanks.
Tried your build. Nothing happens.
The new screen recorder is merged in com.samsung.android.app.smartcapture.
it provides the screenshot tile and recorder one. the recorder is a lot better than the previus one. 

about the behavior of reboot i would be nice to not show it in  lockscreen. and add a toggle for replace for reboot to recovery by system default action. in smart manager you can configure your device to reboot at nights so it doesnot starts rooted. recovery mode seems to be the only way to root since ramdisk is not part of kernel anymore.

EDXPOSED LOG:
02-12 13:53:17.770  7441  7441 E EdXposed-Bridge: android.content.ActivityNotFoundException: Unable to find explicit activity class {com.sec.app.screenrecorder/com.sec.app.screenrecorder.activity.LauncherActivity}; have you declared this activity in your AndroidManifest.xml?
02-12 13:53:17.770  7441  7441 E EdXposed-Bridge: 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2069)
02-12 13:53:17.770  7441  7441 E EdXposed-Bridge: 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1717)
02-12 13:53:17.770  7441  7441 E EdXposed-Bridge: 	at android.app.ContextImpl.startActivity(ContextImpl.java:999)
02-12 13:53:17.770  7441  7441 E EdXposed-Bridge: 	at android.app.ContextImpl.startActivity(ContextImpl.java:970)
02-12 13:53:17.770  7441  7441 E EdXposed-Bridge: 	at android.content.ContextWrapper.startActivity(ContextWrapper.java:389)
02-12 13:53:17.770  7441  7441 E EdXposed-Bridge: 	at android.content.ContextWrapper.startActivity(ContextWrapper.java:389)
02-12 13:53:17.770  7441  7441 E EdXposed-Bridge: 	at sb.firefds.q.firefdskit.actionViewModels.ScreenRecordActionViewModel.startScreenRecord(ScreenRecordActionViewModel.java:44)
02-12 13:53:17.770  7441  7441 E EdXposed-Bridge: 	at sb.firefds.q.firefdskit.actionViewModels.ScreenRecordActionViewModel.onPress(ScreenRecordActionViewModel.java:31)
02-12 13:53:17.770  7441  7441 E EdXposed-Bridge: 	at com.samsung.android.globalactions.presentation.view.GlobalActionsContentItemView.lambda$setViewAttrs$4$GlobalActionsContentItemView(GlobalActionsContentItemView.java:143)
02-12 13:53:17.770  7441  7441 E EdXposed-Bridge: 	at com.samsung.android.globalactions.presentation.view.-$$Lambda$GlobalActionsContentItemView$Ph46jXgNd3y2rgt6J5Na8kAd5lw.onClick(Unknown Source:2)
02-12 13:53:17.770  7441  7441 E EdXposed-Bridge: 	at android.view.View.performClick(View.java:7870)
02-12 13:53:17.770  7441  7441 E EdXposed-Bridge: 	at android.view.View.performClickInternal(View.java:7839)
02-12 13:53:17.770  7441  7441 E EdXposed-Bridge: 	at android.view.View.access$3600(View.java:886)
02-12 13:53:17.770  7441  7441 E EdXposed-Bridge: 	at android.view.View$PerformClick.run(View.java:29315)
02-12 13:53:17.770  7441  7441 E EdXposed-Bridge: 	at android.os.Handler.handleCallback(Handler.java:883)
02-12 13:53:17.770  7441  7441 E EdXposed-Bridge: 	at android.os.Handler.dispatchMessage(Handler.java:100)
02-12 13:53:17.770  7441  7441 E EdXposed-Bridge: 	at android.os.Looper.loop(Looper.java:237)
02-12 13:53:17.770  7441  7441 E EdXposed-Bridge: 	at android.app.ActivityThread.main(ActivityThread.java:7762)
02-12 13:53:17.770  7441  7441 E EdXposed-Bridge: 	at java.lang.reflect.Method.invoke(Native Method)
02-12 13:53:17.770  7441  7441 E EdXposed-Bridge: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
02-12 13:53:17.770  7441  7441 E EdXposed-Bridge: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1047)
02-12 13:53:17.770  7441  7441 I EdXposed-Bridge: Activity not found - ScreenCapture. Trying natively
02-12 13:53:17.771  7441  7441 E EdXposed-Bridge: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
02-12 13:53:17.771  7441  7441 E EdXposed-Bridge: 	at de.robv.android.xposed.XposedHelpers.callMethod(XposedHelpers.java:1263)
02-12 13:53:17.771  7441  7441 E EdXposed-Bridge: 	at sb.firefds.q.firefdskit.actionViewModels.ScreenRecordActionViewModel.startScreenRecord(ScreenRecordActionViewModel.java:52)
02-12 13:53:17.771  7441  7441 E EdXposed-Bridge: 	at sb.firefds.q.firefdskit.actionViewModels.ScreenRecordActionViewModel.onPress(ScreenRecordActionViewModel.java:31)
02-12 13:53:17.771  7441  7441 E EdXposed-Bridge: 	at com.samsung.android.globalactions.presentation.view.GlobalActionsContentItemView.lambda$setViewAttrs$4$GlobalActionsContentItemView(GlobalActionsContentItemView.java:143)
02-12 13:53:17.771  7441  7441 E EdXposed-Bridge: 	at com.samsung.android.globalactions.presentation.view.-$$Lambda$GlobalActionsContentItemView$Ph46jXgNd3y2rgt6J5Na8kAd5lw.onClick(Unknown Source:2)
02-12 13:53:17.771  7441  7441 E EdXposed-Bridge: 	at android.view.View.performClick(View.java:7870)
02-12 13:53:17.771  7441  7441 E EdXposed-Bridge: 	at android.view.View.performClickInternal(View.java:7839)
02-12 13:53:17.771  7441  7441 E EdXposed-Bridge: 	at android.view.View.access$3600(View.java:886)
02-12 13:53:17.771  7441  7441 E EdXposed-Bridge: 	at android.view.View$PerformClick.run(View.java:29315)
02-12 13:53:17.771  7441  7441 E EdXposed-Bridge: 	at android.os.Handler.handleCallback(Handler.java:883)
02-12 13:53:17.771  7441  7441 E EdXposed-Bridge: 	at android.os.Handler.dispatchMessage(Handler.java:100)
02-12 13:53:17.771  7441  7441 E EdXposed-Bridge: 	at android.os.Looper.loop(Looper.java:237)
02-12 13:53:17.771  7441  7441 E EdXposed-Bridge: 	at android.app.ActivityThread.main(ActivityThread.java:7762)
02-12 13:53:17.771  7441  7441 E EdXposed-Bridge: 	at java.lang.reflect.Method.invoke(Native Method)
02-12 13:53:17.771  7441  7441 E EdXposed-Bridge: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
02-12 13:53:17.771  7441  7441 E EdXposed-Bridge: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1047)

**Comment by Firefds** [comment]
@NULLO0B Thank you so much for the info about screen recorder, this make much more sense than what I was trying to do and I think it's working.
Please check this out - 
[FirefdsKit_Q_0.0.3.0-ALPHA-3-debug.apk.zip](https://github.com/Firefds/FirefdsKit/files/4194936/FirefdsKit_Q_0.0.3.0-ALPHA-3-debug.apk.zip)

**Comment by NULL0B** [comment]
> @NULLO0B Thank you so much for the info about screen recorder, this make much more sense than what I was trying to do and I think it's working.
> Please check this out -
> [FirefdsKit_Q_0.0.3.0-ALPHA-3-debug.apk.zip](https://github.com/Firefds/FirefdsKit/files/4194936/FirefdsKit_Q_0.0.3.0-ALPHA-3-debug.apk.zip)

OHH WORKING LIKE CHARM!!
Remember remove text "samsung screen recorder needs to be installed"  "to smart capture" if you have telegram sendme an email i can be your tester android 10.i can help with icons strings in spanish. and even propose commits.

**Comment by Firefds** [comment]
Great! So glad to hear that!
