### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ily4RT** [Firefds/FirefdsKit#7]
**Describe the bug**
The app crashes after 3 seconds of being in it, despite the fact that the functions I enabled work, the standard phone app "settings" also crashes. All applications that are changed, as if they see that they are doing something indecent and fly out. The camera shows errors in the background, although it takes photos and saves them. Well, in the end, I note that the new reboot icons are a little out of style, although they are made very nicely

**Device:**
 - Device: [Galaxy Note 10+]
 - Chipset: [Exynos]
 - Model: [SM-G975F]

**Comment by Firefds** [comment]
Hi @ily4RT, thank you for the issue.
Please make sure you don't have any old Firefds Kit modules on your device.
Uninstall the one your currently have and reboot, install and reboot again.
Also, I will need some more information such as app version, android version,  xposed logs, android logs, screenshots (reboot icons for example)

**Comment by ily4RT** [comment]
![Screenshot_20200216-181903_EdXposed Installer](https://user-images.githubusercontent.com/58047551/74607322-177ea800-50e9-11ea-9948-b0389ac9532c.jpg)
![Screenshot_20200216-181725_EdXposed Installer](https://user-images.githubusercontent.com/58047551/74607327-21a0a680-50e9-11ea-9777-931b94ce64ca.jpg)
![Screenshot_20200216-181651_EdXposed Installer](https://user-images.githubusercontent.com/58047551/74607330-282f1e00-50e9-11ea-86d5-cd8070ce19d4.jpg)
![Screenshot_20200216-181453_Gallery](https://user-images.githubusercontent.com/58047551/74607340-3c731b00-50e9-11ea-856f-01a552427c10.jpg)
![Screenshot_20200216-182952_Settings](https://user-images.githubusercontent.com/58047551/74607509-6aa52a80-50ea-11ea-913c-3be4b5f65e22.jpg)

**Comment by Firefds** [comment]
Oh!! You are using a very old and undated Ed Xposed installer that doesn't work with Android Q.
You need to uninstall that and use https://github.com/ElderDrivers/EdXposedManager/releases instead.
I also recommend, once you download EdXposed Manager, to install the canary version of EdXposed v4.6.1
